version: '3.8'

services:  
  policy-remote-service:
    image: policy-remote-service
    container_name: policy-remote-service
    build:
      context: ../policy-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - opa
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=info"
      - "--addr=0.0.0.0:8181"
      - "/bundle"
    volumes:
      - ./policies:/bundle/policies
      - ./.manifest:/bundle/.manifest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  opal-server:
    image: permitio/opal-server:0.3.1
    container_name: opal-server
    ports:
      - "7002:7002"
    environment:
      OPAL_POLICY_REPO_URL: "https://github.com/andrekachur/opal-policies"
      OPAL_POLICY_REPO_BRANCH: "master"
      OPAL_ENABLE_ADMIN_API: "true"
      OPAL_LOG_LEVEL: "DEBUG"
    depends_on:
      - opa

  opal-client:
    image: permitio/opal-client:latest
    container_name: opal-client
    environment:
      OPAL_SERVER_URL: "http://opal-server:7002"
      POLICY_AGENT_ADDRESS: "http://opa:8181"
      OPAL_CLIENT_TOKEN: "super-secret-token"
    depends_on:
      - opa
      - opal-server
